-- CREATING A DIRECTORY 
CREATE OR REPLACE DIRECTORY sales_directory as 'C:\sales_dir\sal';
-- GRANTING READ PERMISSION TO SYS USER ON SALES_DIRECTORY
GRANT READ ON  DIRECTORY sales_directory TO sys;

drop table sales_data;

-- CREATING AN EXTERNAL TABLE LINK TO THE CSV FILE
CREATE TABLE sales_data (ORDERNUMBER NUMBER(8,2), QUANTITYORDERED NUMBER (6,1), PRICEEACH NUMBER(10,3),ORDERLINENUMBER NUMBER(7,3)
 , SALES VARCHAR(30) ,ORDERDATE VARCHAR(40) ,STATUS VARCHAR(30) ,QTR_ID VARCHAR(30),MONTH_ID NUMBER(5),
 YEAR_ID VARCHAR(30),PRODUCTLINE VARCHAR(40) ,MSRP VARCHAR(30) ,PRODUCTCODE VARCHAR(30),CUSTOMERNAME VARCHAR(40),PHONE VARCHAR(40),
 ADDRESSLINE1 VARCHAR(40),ADDRESSLINE2 VARCHAR(40),CITY VARCHAR(35),STATE VARCHAR(30),POSTALCODE VARCHAR(25),COUNTRY VARCHAR(25),
 TERRITORY VARCHAR (30),CONTACTLASTNAME VARCHAR(30),CONTACTFIRSTNAME VARCHAR(40),DEALSIZE VARCHAR(30))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER
                            DEFAULT DIRECTORY sales_directory
                            ACCESS PARAMETERS
                            (FIELDS TERMINATED BY ",")
                            LOCATION ('sales_data.csv'))
                            REJECT LIMIT 99;
-- SELECTING DATA FROM EXTERNAL TABLE
SELECT * FROM sales_data;